import type { ArchiveProject } from "@/types";

export const archiveProjects: ArchiveProject[] = [
  { title: "Aurora Brand System", location: "Shanghai", services: "Brand Identity", year: "2026", url: "#" },
  { title: "Osmo Packaging Suite", location: "Shenzhen", services: "Packaging", year: "2026", url: "#" },
  { title: "Northline Art Festival", location: "Beijing", services: "Campaign", year: "2026", url: "#" },
  { title: "Flow Wayfinding", location: "Chengdu", services: "Environmental", year: "2026", url: "#" },
  { title: "Studio Index Rebrand", location: "Hangzhou", services: "Branding", year: "2025", url: "#" },
  { title: "Penta Typeface Design", location: "Guangzhou", services: "Type Design", year: "2025", url: "#" },
  { title: "Meridian Hotel Experience", location: "Sanya", services: "Spatial Design", year: "2025", url: "#" },
  { title: "Cascade Digital Brand", location: "Shanghai", services: "Digital Design", year: "2025", url: "#" },
  { title: "Horizon Annual Report", location: "Beijing", services: "Editorial", year: "2025", url: "#" },
  { title: "Prism Exhibition Design", location: "Shenzhen", services: "Exhibition", year: "2024", url: "#" },
  { title: "Lattice UI Kit", location: "Hangzhou", services: "UI Design", year: "2024", url: "#" },
  { title: "Echo Music Festival", location: "Chengdu", services: "Campaign", year: "2024", url: "#" },
  { title: "Vessel Product Line", location: "Guangzhou", services: "Packaging", year: "2024", url: "#" },
  { title: "Nexus Conference", location: "Shanghai", services: "Event Design", year: "2024", url: "#" },
  { title: "Drift Magazine", location: "Beijing", services: "Editorial", year: "2024", url: "#" },
  { title: "Hive Coworking Space", location: "Shenzhen", services: "Environmental", year: "2024", url: "#" },
  { title: "Reel Film Festival", location: "Xiamen", services: "Campaign", year: "2024", url: "#" },
  { title: "Pulse Health App", location: "Hangzhou", services: "Digital Design", year: "2024", url: "#" },
  { title: "Flora Tea Brand", location: "Kunming", services: "Branding", year: "2023", url: "#" },
  { title: "Grid Architecture", location: "Shanghai", services: "Branding", year: "2023", url: "#" },
  { title: "Wave Sound System", location: "Shenzhen", services: "Packaging", year: "2023", url: "#" },
  { title: "Loom Textile Co", location: "Guangzhou", services: "Brand Identity", year: "2023", url: "#" },
  { title: "Beam Lighting", location: "Zhongshan", services: "Product Design", year: "2023", url: "#" },
  { title: "Tide Beach Resort", location: "Sanya", services: "Branding", year: "2023", url: "#" },
  { title: "Ash Ceramics", location: "Jingdezhen", services: "Packaging", year: "2023", url: "#" },
  { title: "Vox Podcast Network", location: "Beijing", services: "Digital Design", year: "2023", url: "#" },
  { title: "Kite Children's Book", location: "Shanghai", services: "Illustration", year: "2023", url: "#" },
  { title: "Mesa Restaurant", location: "Chengdu", services: "Branding", year: "2022", url: "#" },
  { title: "Dune Fashion Label", location: "Shenzhen", services: "Branding", year: "2022", url: "#" },
  { title: "Onyx Jewelry", location: "Guangzhou", services: "Packaging", year: "2022", url: "#" },
  { title: "Vibe Music Platform", location: "Beijing", services: "UI Design", year: "2022", url: "#" },
  { title: "Ridge Outdoor Co", location: "Kunming", services: "Branding", year: "2022", url: "#" },
  { title: "Aura Skincare", location: "Shanghai", services: "Packaging", year: "2022", url: "#" },
  { title: "Strata Office", location: "Beijing", services: "Environmental", year: "2022", url: "#" },
  { title: "Chord Music School", location: "Hangzhou", services: "Branding", year: "2022", url: "#" },
  { title: "Fjord Seafood", location: "Qingdao", services: "Packaging", year: "2021", url: "#" },
  { title: "Grain Bakery", location: "Shanghai", services: "Brand Identity", year: "2021", url: "#" },
  { title: "Lens Photography", location: "Beijing", services: "Branding", year: "2021", url: "#" },
  { title: "Mint Fintech", location: "Shenzhen", services: "Digital Design", year: "2021", url: "#" },
  { title: "Pearl Hotel Group", location: "Xiamen", services: "Branding", year: "2021", url: "#" },
  { title: "Quartz Watches", location: "Shenzhen", services: "Packaging", year: "2021", url: "#" },
  { title: "Rust Industrial", location: "Wuhan", services: "Branding", year: "2021", url: "#" },
  { title: "Silk Fashion Week", location: "Hangzhou", services: "Campaign", year: "2020", url: "#" },
  { title: "Tonic Wellness", location: "Shanghai", services: "Packaging", year: "2020", url: "#" },
  { title: "Umber Coffee Co", location: "Kunming", services: "Branding", year: "2020", url: "#" },
  { title: "Vault Storage", location: "Beijing", services: "Environmental", year: "2020", url: "#" },
  { title: "Wing Aviation", location: "Chengdu", services: "Branding", year: "2020", url: "#" },
  { title: "Xenon Lab", location: "Shenzhen", services: "Digital Design", year: "2020", url: "#" },
  { title: "Yarn Textiles", location: "Guangzhou", services: "Branding", year: "2020", url: "#" },
  { title: "Zinc Architecture", location: "Shanghai", services: "Brand Identity", year: "2020", url: "#" },
  { title: "Atlas Travel", location: "Beijing", services: "Digital Design", year: "2019", url: "#" },
  { title: "Birch Paper Co", location: "Hangzhou", services: "Packaging", year: "2019", url: "#" },
  { title: "Cedar Furniture", location: "Guangzhou", services: "Branding", year: "2019", url: "#" },
  { title: "Dune Architecture", location: "Shanghai", services: "Branding", year: "2019", url: "#" },
  { title: "Ember Candle Co", location: "Shenzhen", services: "Packaging", year: "2019", url: "#" },
  { title: "Flint Tools", location: "Beijing", services: "Product Design", year: "2019", url: "#" },
  { title: "Grove Organic", location: "Kunming", services: "Branding", year: "2019", url: "#" },
  { title: "Haze Perfume", location: "Shanghai", services: "Packaging", year: "2019", url: "#" },
  { title: "Iris Eyewear", location: "Shenzhen", services: "Branding", year: "2019", url: "#" },
  { title: "Jade Tea House", location: "Hangzhou", services: "Brand Identity", year: "2019", url: "#" },
  { title: "Kite Festival", location: "Weifang", services: "Campaign", year: "2019", url: "#" },
  { title: "Lake Gallery", location: "Hangzhou", services: "Exhibition", year: "2019", url: "#" },
  { title: "Mist Brewery", location: "Qingdao", services: "Packaging", year: "2019", url: "#" },
  { title: "Nova Cosmetics", location: "Guangzhou", services: "Branding", year: "2019", url: "#" },
  { title: "Opal Lighting", location: "Zhongshan", services: "Product Design", year: "2019", url: "#" },
  { title: "Pine Resort", location: "Sanya", services: "Branding", year: "2019", url: "#" },
];
